modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="animalexplorer"
version="0.0.0.2"
displayName="AnimalExplorer Rebith"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://www.curseforge.com/minecraft/mc-mods/animal-explorer-rebith"
logoFile="logo.png"
authors="Mathanos"

[[dependencies.animalexplorer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




